# Generated by Django 6.0.3 on 2026-03-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="attack",
            field=models.PositiveSmallIntegerField(default=50, verbose_name="Ataque"),
        ),
        migrations.AddField(
            model_name="creature",
            name="defense",
            field=models.PositiveSmallIntegerField(default=50, verbose_name="Defensa"),
        ),
        migrations.AddField(
            model_name="creature",
            name="hp",
            field=models.PositiveSmallIntegerField(default=50, verbose_name="HP"),
        ),
        migrations.AddField(
            model_name="creature",
            name="speed",
            field=models.PositiveSmallIntegerField(
                default=50, verbose_name="Velocidad"
            ),
        ),
    ]
