# Generated by Django 6.0.3 on 2026-03-20 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0002_add_stats_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creature",
            name="attack",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
                verbose_name="Ataque",
            ),
        ),
        migrations.AlterField(
            model_name="creature",
            name="defense",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
                verbose_name="Defensa",
            ),
        ),
        migrations.AlterField(
            model_name="creature",
            name="hp",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
                verbose_name="HP",
            ),
        ),
        migrations.AlterField(
            model_name="creature",
            name="speed",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
                verbose_name="Velocidad",
            ),
        ),
    ]
